defaultconfig = {
    "v2_menu_styling": True,
    "v2_key_styling_menu": "F2",
    "v2_show_in_contextmenu": True,
    "v3": [
        {
            "active": True,
            "Category": "Backcolor (via class)",
            "Hotkey": "Alt+q",
            "Setting": "bg_yellow",
            "Show_in_menu": True,
            "Text_in_menu": "yellow",
            "Text_in_menu_styling": "#ffff00",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "bYe",
            "extrabutton_tooltip": "class background yellow"
        },
        {
            "active": True,
            "Category": "Backcolor (via class)",
            "Hotkey": "Alt+w",
            "Setting": "bg_green",
            "Show_in_menu": True,
            "Text_in_menu": "green",
            "Text_in_menu_styling": "#00ff00",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "bGr",
            "extrabutton_tooltip": "class background green"
        },
        {
            "active": True,
            "Category": "Backcolor (via class)",
            "Hotkey": "Alt+e",
            "Setting": "bg_blue",
            "Show_in_menu": True,
            "Text_in_menu": "blue",
            "Text_in_menu_styling": "#00ffff",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "bBl",
            "extrabutton_tooltip": "class background blue"
        },
        {
            "active": True,
            "Category": "Backcolor (via class)",
            "Hotkey": "Alt+r",
            "Setting": "bg_red",
            "Show_in_menu": True,
            "Text_in_menu": "red",
            "Text_in_menu_styling": "#fd9796",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "bRe",
            "extrabutton_tooltip": "class background red"
        },
        {
            "Category": "Forecolor (via class)",
            "Hotkey": "Alt+shift+w",
            "Setting": "fg_green",
            "Show_in_menu": True,
            "Text_in_menu": "font-color green",
            "Text_in_menu_styling": "#00aa00",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "fG",
            "extrabutton_tooltip": "font-color green"
        },
        {
            "Category": "Forecolor (via class)",
            "Hotkey": "Alt+shift+e",
            "Setting": "fg_blue",
            "Show_in_menu": True,
            "Text_in_menu": "font-color blue",
            "Text_in_menu_styling": "#0000ff",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "fB",
            "extrabutton_tooltip": "font-color blue"
        },
        {
            "Category": "Forecolor (via class)",
            "Hotkey": "Alt+shift+r",
            "Setting": "fg_red",
            "Show_in_menu": True,
            "Text_in_menu": "font-color red",
            "Text_in_menu_styling": "#ff0000",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "fR",
            "extrabutton_tooltip": "font-color red"
        },
        {
            "Category": "class (other)",
            "Hotkey": "Alt+shift+s",
            "Setting": "bigger_font",
            "Show_in_menu": True,
            "Target group in menu": "",
            "Text_in_menu": "bigger",
            "Text_in_menu_styling": "font-size: 125%;",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "bb",
            "extrabutton_tooltip": "apply class 'bigger font'"
        },
        {
            "Category": "class (other)",
            "Hotkey": "Alt+shift+b",
            "Setting": "bold_bigger",
            "Show_in_menu": True,
            "Target group in menu": "",
            "Text_in_menu": "bold_bigger",
            "Text_in_menu_styling": "font-weight: bold;font-size: 125%;",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "bb",
            "extrabutton_tooltip": "apply class 'bold,bigger'"
        },
        {
            "Category": "class (other)",
            "Hotkey": "Alt+shift+f",
            "Setting": "bold_underlined",
            "Show_in_menu": True,
            "Target group in menu": "",
            "Text_in_menu": "bold_underlined",
            "Text_in_menu_styling": "font-weight: bold; text-decoration: underline;",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "bb",
            "extrabutton_tooltip": "apply class 'bold,bigger'"
        },
        {
            "Category": "class (other)",
            "Hotkey": "Alt+shift+g",
            "Setting": "bold_red",
            "Show_in_menu": True,
            "Target group in menu": "",
            "Text_in_menu": "bold_bgRED",
            "Text_in_menu_styling": "font-weight: bold; color: red;",
            "Text_in_menu_styling_nightmode": "font-weight: bold; color: #da0000;",
            "extrabutton_show": False,
            "extrabutton_text": "br",
            "extrabutton_tooltip": "apply class 'bold_red'"
        },
        {
            "Category": "font size (via class)",
            "Hotkey": "Alt+shift+4",
            "Setting": "font_size_80",
            "Show_in_menu": True,
            "Target group in menu": "",
            "Text_in_menu": "font size 80%",
            "Text_in_menu_styling": "80%",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "80",
            "extrabutton_tooltip": "set font size to 80%"
        },
        {
            "Category": "font size (via class)",
            "Hotkey": "Alt+shift+5",
            "Setting": "font_size_130",
            "Show_in_menu": True,
            "Target group in menu": "",
            "Text_in_menu": "bigger font",
            "Text_in_menu_styling": "130%",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "130",
            "extrabutton_tooltip": "set font size to 130%"
        },
    ]
} 
