defaultconfig = {
    "update_level": "1589114109",
    "v2_menu_styling": True,
    "v2_key_styling_menu": "F2",
    "v2_key_styling_undo": "Alt+r",
    "v2_show_in_contextmenu": True,
    "v3": [
        {
            "active": True,
            "Category": "Backcolor (via class)",
            "Hotkey": "Alt+Q",
            "Setting": "bg_yellow",
            "Show_in_menu": True,
            "Text_in_menu": "yellow",
            "Text_in_menu_styling": "#ffff00",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "bYe",
            "extrabutton_tooltip": "class background yellow",
        },
        {
            "active": True,
            "Category": "Backcolor (via class)",
            "Hotkey": "Alt+W",
            "Setting": "bg_green",
            "Show_in_menu": True,
            "Text_in_menu": "green",
            "Text_in_menu_styling": "#00ff00",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "bGr",
            "extrabutton_tooltip": "class background green",
        },
        {
            "active": True,
            "Category": "Backcolor (via class)",
            "Hotkey": "Alt+E",
            "Setting": "bg_blue",
            "Show_in_menu": True,
            "Text_in_menu": "blue",
            "Text_in_menu_styling": "#00ffff",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "bBl",
            "extrabutton_tooltip": "class background blue",
        },
        {
            "active": True,
            "Category": "Backcolor (via class)",
            "Hotkey": "Alt+T",
            "Setting": "bg_red",
            "Show_in_menu": True,
            "Text_in_menu": "red",
            "Text_in_menu_styling": "#fd9796",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "bRe",
            "extrabutton_tooltip": "class background red",
        },
        {
            "Category": "Forecolor (via class)",
            "Hotkey": "Shift+Alt+W",
            "Setting": "fg_green",
            "Show_in_menu": True,
            "Text_in_menu": "font-color green",
            "Text_in_menu_styling": "#00aa00",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "fG",
            "extrabutton_tooltip": "font-color green",
        },
        {
            "Category": "Forecolor (via class)",
            "Hotkey": "Shift+Alt+E",
            "Setting": "fg_blue",
            "Show_in_menu": True,
            "Text_in_menu": "font-color blue",
            "Text_in_menu_styling": "#0000ff",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "fB",
            "extrabutton_tooltip": "font-color blue",
        },
        {
            "Category": "Forecolor (via class)",
            "Hotkey": "Shift+Alt+R",
            "Setting": "fg_red",
            "Show_in_menu": True,
            "Text_in_menu": "font-color red",
            "Text_in_menu_styling": "#ff0000",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "fR",
            "extrabutton_tooltip": "font-color red",
        },
        {
            "Category": "class (other)",
            "Hotkey": "Shift+Alt+B",
            "Setting": "bold_bigger",
            "Show_in_menu": True,
            "Target group in menu": "",
            "Text_in_menu": "bold_bigger",
            "Text_in_menu_styling": "font-weight: bold;font-size: 125%;",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "bb",
            "extrabutton_tooltip": "apply class 'bold,bigger'",
            "surround_with_div_tag": False,
        },
        {
            "Category": "class (other)",
            "Hotkey": "Shift+Alt+F",
            "Setting": "bold_underlined",
            "Show_in_menu": True,
            "Target group in menu": "",
            "Text_in_menu": "bold_underlined",
            "Text_in_menu_styling": "font-weight: bold; text-decoration: underline;",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "bb",
            "extrabutton_tooltip": "apply class 'bold,bigger'",
            "surround_with_div_tag": False,
        },
        {
            "Category": "class (other)",
            "Hotkey": "Shift+Alt+G",
            "Setting": "bold_red",
            "Show_in_menu": True,
            "Target group in menu": "",
            "Text_in_menu": "bold_bgRED",
            "Text_in_menu_styling": "font-weight: bold; color: red;",
            "Text_in_menu_styling_nightmode": "font-weight: bold; color: #da0000;",
            "extrabutton_show": False,
            "extrabutton_text": "br",
            "extrabutton_tooltip": "apply class 'bold_red'",
            "surround_with_div_tag": False,
        },
        {
            "Category": "class (other), wrapped in div",
            "Hotkey": "Shift+Alt+H",
            "Setting": "red_box",
            "Show_in_menu": True,
            "Target group in menu": "",
            "Text_in_menu": "red box",
            "Text_in_menu_styling": "border:solid; border-color:red; background-color: #ffc5c5; margin-left:40px;",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "br",
            "extrabutton_tooltip": "red box",
            "surround_with_div_tag": False,
        },
        {
            "Category": "class (other), wrapped in div",
            "Hotkey": "Shift+Alt+S",
            "Setting": "small_and_narrow",
            "Show_in_menu": True,
            "Target group in menu": "",
            "Text_in_menu": "small_and_narrow",
            "Text_in_menu_styling": "font-size:80% !important; line-height: 80%;",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "br",
            "extrabutton_tooltip": "red box",
            "surround_with_div_tag": False,
        },
        {
            "Category": "font size (via class)",
            "Hotkey": "Shift+Alt+4",
            "Setting": "font_size_80",
            "Show_in_menu": True,
            "Target group in menu": "",
            "Text_in_menu": "font size 80%",
            "Text_in_menu_styling": "80%",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "80",
            "extrabutton_tooltip": "set font size to 80%",
        },
        {
            "Category": "font size (via class)",
            "Hotkey": "Shift+Alt+5",
            "Setting": "font_size_130",
            "Show_in_menu": True,
            "Target group in menu": "",
            "Text_in_menu": "bigger font",
            "Text_in_menu_styling": "130%",
            "Text_in_menu_styling_nightmode": "",
            "extrabutton_show": False,
            "extrabutton_text": "130",
            "extrabutton_tooltip": "set font size to 130%",
        }
    ]
} 
